### ISSUE TITLE
created pull request on changes done in choose_first function

### ISSUE THREAD

**Issue by adityarajendrashanbhag** [laxmishigoli1152/Tic-Tac-Toe-Game#1]

**Comment by adityarajendrashanbhag** [comment]
i have made some change on the code, a lil bit of spacing and extra variables have been added and added some extra functions for the smooth functioning of code

**Comment by laxmishigoli1152** [comment]
i have seen the changes , let me just run the code and let u know

**Comment by adityarajendrashanbhag** [comment]
ill just create a pull request and compare it mam

**Comment by laxmishigoli1152** [comment]
i have seen the code and its working fine. Thank you
